version: '3.8'

services:
  db:
    image: postgres:16
    container_name: vsms_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vsms_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/db  # Mount local db folder so we can easily run schema scripts

volumes:
  postgres_data:
